DROP TABLE IF EXISTS DISTRIBUTION_TYPE;
CREATE TABLE [DISTRIBUTION_TYPE]
(
    [ID] INTEGER  NOT NULL PRIMARY KEY,
    [DOCKER] TEXT,
    [JUPYTER_NOTEBOOK] TEXT,
    [JAVA] TEXT,
    [COMPRESSED] TEXT,
    [EXE] TEXT
);

DROP TABLE IF EXISTS SUPPORT_TYPE;
CREATE TABLE [SUPPORT_TYPE]
(
    [ID] INTEGER  NOT NULL PRIMARY KEY,
    [FREE_SUPPORT] TEXT,
    [COMMERCIAL_SUPPORT] TEXT,
    [DISCUSSION_FORUM] TEXT
);


DROP TABLE IF EXISTS AI_TECHNICAL_CATEGORY;
CREATE TABLE [AI_TECHNICAL_CATEGORY]
(
    [ID] INTEGER  NOT NULL PRIMARY KEY,
	[EXPLAINABLE_AI] TEXT,
	[VERIFIABLE_AI] TEXT,
	[PHYSICAL_AI] TEXT,
	[INTEGRATIVE_AI] TEXT,
	[COLLABORATIVE_AI] TEXT,
	[ALGORITHM_SELECTION] TEXT,
	[COMPUTATIONAL_LOGIC] TEXT,
	[COMPUTER_VISION] TEXT,
	[CONSTRAINTS_AND_SAT] TEXT,
	[DECISION_SUPPORT_SYSTEMS] TEXT,
	[HEURISTIC_SEARCH] TEXT,
	[KNOWLEDGE_REPRESENTATION] TEXT,
	[MACHINE_LEARNING] TEXT,
	[MULTI-AGENT_SYSTEMS] TEXT,
	[DEEP_LEARNING] TEXT,
	[PLANNING] TEXT,
	[NATURAL_LANGUAGE_PROCESSING] TEXT,
	[SPEECH/AUDIO_PROCESSING] TEXT,
	[DIALOGUE_PROCESSING] TEXT,
	[PROBABILISTIC_MODELS] TEXT,
	[SEMANTIC_WEB] TEXT,
	[ROBOTICS] TEXT,
	[REASONING] TEXT,
	[OTHER] TEXT
);

DROP TABLE IF EXISTS AI_BUSINESS_CATEGORY;
CREATE TABLE [AI_BUSINESS_CATEGORY]
(
    [ID] INTEGER  NOT NULL PRIMARY KEY,
	[AI_FOR_AGRICULTURE] TEXT,
	[AI_IN_HEALTH] TEXT,
	[AI_FOR_CITIZEN_SERVICES_&_EDUCATION] TEXT,
	[AI_FOR_ROBOTICS] TEXT,
	[AI_FOR_INDUSTRY_AND_MANUFACTURING] TEXT,
	[AI_IN_AUTONOMOUS_DRIVING_AND_MOBILITY] TEXT,
	[AI_FOR_ART_AND_MUSIC] TEXT,
	[AI_FOR_ENVIRONMENT_AND_SUSTAINABILITY] TEXT,
	[AI_FOR_IOT] TEXT,
	[AI_FOR_CYBERSECURITY] TEXT,
	[AI_FOR_MEDIA] TEXT,
	[AI_FOR_TELECOMMUNICATION] TEXT,
	[AI_FOR_FINANCE_&_INSURANCE] TEXT,
	[AI_FOR_LAW] TEXT,
	[AI_IN_RETAIL_AND_ECOMMERCE] TEXT,
	[AI_IN_SOFTWARE_ENGINEERING] TEXT,
	[AI_IN_HUMAN_RESOURCES] TEXT,
	[AI_FOR_TRUST_AND_PRIVACY] TEXT,
	[AI_FOR_AMBIENT_INTELLIGENCE] TEXT,
	[AI_FOR_SPACE] TEXT,
	[AI_FOR_AIR_TRAFFIC_MANAGEMENT] TEXT,
	[AI_FOR_FASHION] TEXT,
	[OTHER] TEXT
);


DROP TABLE IF EXISTS KEYWORD;
CREATE TABLE [KEYWORD]
(
    [ID] INTEGER  NOT NULL PRIMARY KEY,
    [NAME] TEXT
);

DROP TABLE IF EXISTS LABEL;
CREATE TABLE [LABEL]
(
    [ID] INTEGER  NOT NULL PRIMARY KEY,
    [ACUMOS_READY] TEXT,
    [BEAT_READY] TEXT,
    [ELG_READY] TEXT,
    [MUNDI_READY] TEXT,
    [BONSEYES_READY] TEXT,
    [VERiFIED_PROVIDER] TEXT,
    [OFFICIAL_RESOURCE] TEXT
);



DROP TABLE IF EXISTS LICENSE;
CREATE TABLE [LICENSE]
(
    [ID] INTEGER  NOT NULL PRIMARY KEY,
    [GPL] TEXT,
    [APACHE] TEXT,
    [LGPL] TEXT,
    [MIT] TEXT,
    [COMMERCIAL] TEXT
);

DROP TABLE IF EXISTS DISTRIBUTION;
CREATE TABLE [DISTRIBUTION]
(
    [ID] INTEGER  NOT NULL PRIMARY KEY,
    [DISTRIBUTION_TYPE_ID] INTEGER NOT NULL,
    [FILENAME] TEXT,
    [FILE_SIZE] INTEGER,
    [CONTENT_TYPE] TEXT,
    [EXECUTION_ENVIRONMENT] TEXT,
    [STORAGE_LINK_BINARY] TEXT,
    [SHA2_HASH] TEXT,
    [CREATED_ON] DATETIME,
	FOREIGN KEY(DISTRIBUTION_TYPE_ID) REFERENCES DISTRIBUTION_TYPE(ID)
);

DROP TABLE IF EXISTS AI_RESOURCE;
CREATE TABLE [AI_RESOURCE]
(
    [ID] INTEGER  NOT NULL PRIMARY KEY,
	[NAME] TEXT NOT NULL,
	[DESCRIPTION] TEXT,
	[HOMEPAGE] TEXT,
	[VERSION] TEXT,
	[VERSION_RELEASE_DATE] DATE,
	[DISTRIBUTION_IDS] INTEGER,
	[AI_TECHNICAL_CATEGORY_IDS] INTEGER,
	[AI_BUSINESS_CATEGORY_IDS] INTEGER,
	[LICENSE_IDS] INTEGER,
	[LICENSE_URL] TEXT,
	[SUPPORT_TYPE_IDS] INTEGER,
	[SUPPORT_URL] TEXT,
	[GDPR_COMPLIANT] INTEGER,
	[PROVIDER] TEXT,
	[AUTHORS] TEXT,
	[LINKED_AI_RESOURCES] INTEGER,
	[KEYWORD_IDS] INTEGER,
	[LABEL_IDS] INTEGER,
    [CREATED_ON] DATETIME,
	FOREIGN KEY(DISTRIBUTION_IDS) REFERENCES DISTRIBUTION(ID),
	FOREIGN KEY(AI_TECHNICAL_CATEGORY_IDS) REFERENCES AI_TECHNICAL_CATEGORY(ID),
	FOREIGN KEY(AI_BUSINESS_CATEGORY_IDS) REFERENCES AI_BUSINESS_CATEGORY(ID),
	FOREIGN KEY(LICENSE_IDS) REFERENCES LICENSE(ID),
	FOREIGN KEY(LINKED_AI_RESOURCES) REFERENCES AI_RESOURCE(ID),
	FOREIGN KEY(KEYWORD_IDS) REFERENCES KEYWORD(ID),
	FOREIGN KEY(LABEL_IDS) REFERENCES LABEL(ID),
	FOREIGN KEY(SUPPORT_TYPE_IDS) REFERENCES SUPPORT_TYPE(ID)
);	


DROP TABLE IF EXISTS DOCUMENT;
CREATE TABLE [DOCUMENT]
(
    [ID] INTEGER  NOT NULL PRIMARY KEY,
    [AI_RESOURCE_ID] INTEGER NOT NULL,
    [FILENAME] TEXT,
    [FILE_SIZE] INTEGER,
    [CONTENT_TYPE] TEXT,
    [STORAGE_LINK_BINARY] TEXT,
    [SHA2_HASH] TEXT,
    [CREATED_ON] DATETIME,
	FOREIGN KEY(AI_RESOURCE_ID) REFERENCES AI_RESOURCE(ID)
);

DROP TABLE IF EXISTS RATING;
CREATE TABLE [RATING]
(
    [ID] INTEGER  NOT NULL PRIMARY KEY,
    [AI_RESOURCE_ID] INTEGER NOT NULL,
    [STARS] INTEGER,
    [REVIEW] TEXT,
    [CREATED_ON] DATETIME,
	FOREIGN KEY(AI_RESOURCE_ID) REFERENCES AI_RESOURCE(ID)
);




